### ISSUE TITLE
ADD Meta Learning Template

### ISSUE THREAD

**Issue by AntonioCarta** [ContinualAI/avalanche#1079]
@HamedHemati

**Comment by HamedHemati** [comment]
As discussed in the previous meeting, creating new templates with the current structure will result in lots of code duplicates. For example if we want to have a separate template for meta-learning based strategies we will probably need at least two different templates like `MetalearningTemplate` and `OnlineMetalearningTemplate` where most of the code is shared with other SGD-based strategies. To avoid this, as suggested by @AntonioCarta (to use mixin classes in Python), I thought about a different template structure as below. It doesn't necessarily have to be exactly like the one below, but separating the different aspects of a learning strategy can make extensions easier without code duplicates and therefore make it easier to maintain the templates: 

<img src="https://user-images.githubusercontent.com/11629528/177012115-4babe6f4-86c0-43b0-b422-b1f69dca331a.png" width=500>

To create a new template one can define the template class with the following pattern:

```python
class NAME(problem_type, observation_type, update_type, base_template)
```
The first three classes are mixin classes, and the last one is the super template class.


Some examples:

```python
class SupervisedTemplate(Supervised, Batch, SGDUpdate, SGDTemplate):
    def __init__(self):
        ...
```
^ this won't break the existing supervised strategies since all callbacks will remain the same.

```python
class OnlineSupervisedMetaTemplate(Supervised, Online, MetaUpdate, SGDTemplate):
    def __init__(self):
        ...
```

** This is just an initial idea on how to change the structure, and of course, the split names can be different.
@AntonioCarta please let me know your opinion about this type of approach.
