### ISSUE TITLE
Different combination of input

### ISSUE THREAD

**Issue by irfanfadhullah** [ContinualAI/avalanche#1141]
Is it possible to change the input or feature for classification.
For example in the initial training, we train the model with 3 input feature (featureA, feature B, and feature C).
After that, we use continual learning to update the model with different number inputs (feature A, feature B, feature C, and feature D).
Is it possible to do that with this ?

**Comment by AndreaCossu** [comment]
Yes, it is possible. The idea is similar to the multi-head model, which incrementally adds new output heads. I suggest you to look at multihead models under `avalanche/models`. You need to expand the first input layer instead of the output layer during the call to `adaptation` (called automatically by avalanche at the end of each training experience).

**Comment by irfanfadhullah** [comment]
I got it. Thanks a lot for the explanation. I will try to do some experiments.

**Comment by irfanfadhullah** [comment]
I have another question, is it possible ot change the the input based on the availability of data? 
For example, the input can be 5 input, 4 input, or 7 input (the number of input is dynamic)

**Comment by AntonioCarta** [comment]
Yes, you can do it just as you can do it for the output. How you do it depends on what you want exactly. Please don't open issues to discuss usage questions.
