### ISSUE TITLE
iCaRL + `eval_every=1` fails

### ISSUE THREAD

**Issue by wistuba** [ContinualAI/avalanche#1281]
iCaRL works as long as I do not use eval_every>0. Then I get following exception:

```
site-packages/avalanche/models/ncm_classifier.py", line 23, in forward
    sqd = torch.cdist(self.class_means[:, :].T, pred_inter)
TypeError: 'NoneType' object is not subscriptable
```

Basically, class_means are used before their assignment.

**Comment by jmin0530** [comment]
I suffered that error, too. I think when iCaRL trains first task, self.class_means is 'None' type.
According to iCaRL code (https://github.com/ContinualAI/avalanche/blob/8ae7bab909a091cb3cc2ad5b46c3df4933529410/avalanche/training/supervised/icarl.py#L181), self.class_means will produced after training task is completed.
But I couldn't solve that error.

**Comment by AntonioCarta** [comment]
@AndreaCossu same as the other issue. Does iCaRL work now?

**Comment by AlbinSou** [comment]
> @AndreaCossu same as the other issue. Does iCaRL work now?

@AntonioCarta I partly fixed this in this [PR 1458](https://github.com/ContinualAI/avalanche/pull/1458). This is an issue that affects Nearest Mean Classifier in general. What I did for now is to turn the NCM to a dynamic module that adapts to unseen classes by setting their vector to a torch.zeros(feature_size), which is the default behavior. However, it still fails to perform the evaluation before training on anything (the very first evaluation step when do_initial=True in PeriodicEval), because in that case it's not possible to know what is the size of the feature vector (in the other case, I take it from the size of already existing feature vectors).

**Comment by AntonioCarta** [comment]
> because in that case it's not possible to know what is the size of the feature vector

can we fix this by adding a special case in the forward pass? example:
```
def forward(...):
    if self._not_initialized:
            # init means with proper size (which is known here)
```

**Comment by AndreaCossu** [comment]
I think so, although the evaluation does not make much sense if you don't have any class prototypes. You are comparing against the same prototype (zero vector) for all classes.

**Comment by AndreaCossu** [comment]
This should be fixed now
