### ISSUE TITLE
Is there any implementation of class Incremental learning using avalanche for image classification or object detection tasks?

### ISSUE THREAD

**Issue by Natarajan-Lakshmanan** [ContinualAI/avalanche#1366]
Also, I have a basic question!
If training on different tasks containing different classes is called Task Incremental learning, then what chnages must be made to transform the task incremental learning to Class incremental learning?
I am a budding learner in this field so any explanations or implementation examples would help me a lot to learn continual learning?

**Comment by zeyuanyin** [comment]
Hi @Natarajan-Lakshmanan, I find one example of class Incremental learning using avalanche for image classification. 

https://github.com/ContinualAI/avalanche/blob/master/examples/naive.py

I don't know why the develops name it ``naive.py`` instead of ``class_incremental.py``, which is harder for users to find it.  Same issue in [issue-1373](https://github.com/ContinualAI/avalanche/issues/1373#issuecomment-1546660581)
