### ISSUE TITLE
Add Automatic Docker Image Release

### ISSUE THREAD

**Issue by vlomonaco** [ContinualAI/avalanche#383]
It would be nice to ship automatically a docker image of avalanche, I think this can be automatize through GitHub Packages. We should check it out!

**Comment by mohzulfikar** [comment]
Hello sir, I want to ask a few questions about this. Because the repo doesn't have `Dockerfile`, might as well create it first. 

So, should the docker image only contains python and this library (along with its dependencies) or it should also install jupyter and serve it? I've found an example for the first one in [here](https://github.com/REMnux/docker/blob/master/ciphey/Dockerfile), although it can be modified so that it starts with python shell or even ipython.

**Comment by vlomonaco** [comment]
Thanks @mohzulfikar I think @ggraffieti has already a dockefile ready, isn't it @ggraffieti? Maybe as @mohzulfikar we can add it to the repo even if we don't work out the automatic docker release yet!
