### ISSUE TITLE
Untied size for train and test stream

### ISSUE THREAD

**Issue by lrzpellegrini** [ContinualAI/avalanche#443]
At the moment Avalanche supports creating scenarios using a lot of helpers/generators. However, these tools constraint the available choice of streams (only "train" and "test" are supported, see #332) and the amount of experiences in the streams.

Currently the following combinations are supported:

- N train experiences, N test experiences
- N train experiences, 1 test experience

This not sufficiently general and doesn't allow for the implementation of various benchmarks that use a different amount of experiences in different streams (for instance, the CV part of A-GEM).

**Comment by AntonioCarta** [comment]
Maybe we need some stream generators? Instead of generating the entire scenario we could provide methods to split a dataset into a stream. This will make it easier to have different train/eval streams.
Some examples:
- splitting a dataset to generate a stream (by class, task, ...)
- splitting a stream (e.g. CV part of A-GEM)
