### ISSUE TITLE
MultiHeadPlugin working incorrectly with Replay

### ISSUE THREAD

**Issue by Mattdl** [ContinualAI/avalanche#502]
For ReplayPlugin there are samples added to the mb_x and mb_y in before_forward. However, in the MultiHeadPlugin only the current experience head is singled out, and this is not conditional on which label/experience the samples are from. Therefore, the replayed samples are predicting from the current head instead of the previous one corresponding to their experience.
Any thoughts on how to solve this?

**Comment by AntonioCarta** [comment]
Thanks for reporting the issue. I'm already working on a new multi-head implementation. I will open a PR soon. 

Avalanche datasets changed a lot since we implemented multi-head models and we now support sample-level task labels. I think the multi-head should be impemented as a pytorch `Module` and take the task labels as additional input and select the head inside the `forward` method. I think this is easier because it moves all the logic inside the model instead of having to modify the model before calling `forward`, which is error-prone.

**Comment by Mattdl** [comment]
This indeed seems a very good approach to me! I was also thinking of having sample-level task labels for this, but good to hear it's already out there (:

**Comment by vlomonaco** [comment]
PR #535 implements the new model logic. Is this already solved @AntonioCarta?
