### ISSUE TITLE
[BACKWARD INCOMPATIBLE] Behavior when training on multiple experiences

### ISSUE THREAD

**Issue by AntonioCarta** [ContinualAI/avalanche#661]
At the moment there are some plugins/strategies broken in a very subtle way. They have different behavior when using
```
for exp in stream:
	strategy.eval(exp)
```
instead of `strategy.eval(stream)`. In particular, `Stream` metrics suffer from this problem. I propose to remove `before/after_{training/eval}`. Metrics should be refactored so that they have the same behavior in the two cases.

IMO, strategies and plugins should always work by processing single experiences iteratively. The fact that `train` also accepts an entire stream is only for the user's convenience. 

I propose to remove `before/after_{training/eval}` callbacks to remove the source of these bugs.

**Comment by vlomonaco** [comment]
It makes total sense to me!

**Comment by AndreaCossu** [comment]
I think in this case metrics like `StreamAccuracy` could not be implemented as they are now since they could not know when to emit the values (since `after_eval` would not be available). As a solution, they could emit the cumulative average after each experience and the user should then pick the he is interested in. 
The reset of such metrics may also be problematic. They would be forced to reset their values on `train_exp` (or similar). In this way, two consecutive calls of `eval` would result in a single (cumulative) `StreamAccuracy` instead of two separate ones. I have to check more carefully possible sources of problems.

**Comment by AntonioCarta** [comment]
> I think in this case metrics like StreamAccuracy could not be implemented as they are now since they could not know when to emit the values (since after_eval would not be available). 

This is expected. The point is that the current usage of these callbacks are already problematic and result in wrong implementations.

If you need to control the training/eval loops you need to do it outside the strategies, and you are free to do whatever you want. This is totally independent from the strategy.
