### ISSUE TITLE
CI Test failing on python 3.8

### ISSUE THREAD

**Issue by AntonioCarta** [ContinualAI/avalanche#974]
`tests.training.test_strategies_accuracy.StrategyTest.test_multihead_cumulative` is failing on python 3.8.
I tested it locally and it is working. Here are the results of two independent runs:

```
TRAIN STREAM ACC:  {0: 0.8823529411764706, 1: 0.864406779661017, 2: 0.859504132231405, 3: 0.859504132231405, 4: 0.8760330578512396}
TRAIN STREAM ACC:  {0: 0.95, 1: 0.95, 2: 1.0, 3: 0.9333333333333333, 4: 0.6974789915966386}
```

the test requires average accuracy above 0.7.

**Comment by ggraffieti** [comment]
Seems that the same test failed for the same reasons in python 3.9 when the create environment action is triggered (see #976). 
Since the same error is triggered in 2 different runs with 2 different python versions, it's pretty clear that the tests are not deterministic, which is an issue by itself. 
Since is always the multihead test that failed, I guess the effect of different initialization or different random seeds is more evident in this case. 

To fix this, the best way is to make this (and potentially all) test deterministic, setting manually all the seeds for all the libraries. I have a piece of code that do that, I can insert it into the test file and see if 2 different runs output the same results.

**Comment by ggraffieti** [comment]
I double-checked (in my pc) and the test are definitely not deterministic. 
I added a piece of code to make them deterministic and now if I launch them few times the results are always the same. 
This is a quick fix only in the file `tests/training/test_strategies_accuracy.py`, we need to insert this "seed initialization" before every test. 
We can make an util function that do that and call it at the start of every test. I'll open an issue to remember this.
